### ISSUE TITLE
How do i get the updated value?

### ISSUE THREAD

**Issue by ghost** [dfreeman/ember-ace#1]
I am struggling to retrieve the updated text from the component. Neither is the value updated nor can i retrieve the updated data via editor.getSession().getValue()); 

Could you provide an example how to get the the updated input from the ace-editor?

thanks a lot!

**Comment by dfreeman** [comment]
@OlmoDalco this component is set up for a "data down, actions up" flow, so if you set an `update` action, that will receive the new value whenever the user makes a change.

```hbs
{{ember-ace value=value update=(action 'valueChanged')}}
```

```js
actions: {
  valueChanged(newValue) {
    // do whatever with the new value here
  }
}
```

If all you want to do is update the original value property in place, you could instead do

```hbs
{{ember-ace value=value update=(action (mut value))}}
```

**Comment by ghost** [comment]
Thanks! <3
