### ISSUE TITLE
Where to install themes and modes?

### ISSUE THREAD

**Issue by x4er0** [dfreeman/ember-ace#12]
Where to put files with themes and modes from https://github.com/ajaxorg/ace/tree/master/lib/ace/mode ?

**Comment by dfreeman** [comment]
Hi @x4er0! You don't need to put the files anywhere—you just include the names of the ones you want to include in your configuration for the addon. See [the Build Configuration section of the README](https://github.com/dfreeman/ember-ace/blob/master/README.md#build-configuration) for an example 🙂

**Comment by panthony** [comment]
Edit:

I don' know how to read a README, sorry it works, my bad 🤡
