### ISSUE TITLE
How to use the extensions

### ISSUE THREAD

**Issue by devotox** [dfreeman/ember-ace#15]
You have the exts array in ember-cli-build.js but how do you actually use the extensions?

**Comment by dfreeman** [comment]
Ace has some (minimal) documentation for the built-in extensions here: https://github.com/ajaxorg/ace/wiki/Extensions

For many of the extensions, just including it and setting a particular option on the editor instance (passed to the [`ready` action](https://github.com/dfreeman/ember-ace#core)) is enough.

For instance, with `ext: ['emmet']` included, you'd [call `editor.setOption('enableEmmet', true)`](https://github.com/ajaxorg/ace/blob/master/demo/emmet.html#L36-L37).

**Comment by devotox** [comment]
Thank you!

**Comment by devotox** [comment]
I tried this but emmet keybindings still dont work. Dont know if this is a ember ace or an actual ace issue

```
	actions: {
		ready(editor) {
			console.log(editor, ace);
			ace.require('ace/ext/emmet');
			ace.require('ace/ext/language_tools');

			editor.setOption('enableEmmet', true);

			editor.commands.addCommand({
				name: 'showKeyboardShortcuts',
				bindKey: { win: 'Ctrl-Alt-H', mac: 'Command-Alt-H' },
				exec(editor) {
					ace.config.loadModule('ace/ext/keybinding_menu', function(module) {
						module.init(editor);
						editor.showKeyboardShortcuts();
					});
				}
			});
		}
	}
```

**Comment by devotox** [comment]
haaaaa needed to load emmet separately
