### ISSUE TITLE
Feature enhancement: Standard CSS height properties for compatibility with flexbox.

### ISSUE THREAD

**Issue by bdiz** [dfreeman/ember-ace#16]
I'm using flexbox to resize the elements in my app. CSS `height` property needs to be changed on the ace editor, but seems the height control here in ember-ace is `lines|minLines|maxLines`. 

Is it possible to use CSS `height|max-height|min-height` properties to resize ember-ace editor?

**Comment by webhive** [comment]
Absolutely agree. It could be gret.

**Comment by dfreeman** [comment]
Apologies for how long this issue sat! What you're describing was actually possible in pre-1.0 releases of this addon, but broke when we added a wrapper div to support autosuggest. You _should_ be able to accomplish this with the [`editorClass` property](https://github.com/dfreeman/ember-ace#sizing) that was added in 1.3.0.
