### ISSUE TITLE
Is this plug-in compatible with Ember 1.3?

### ISSUE THREAD

**Issue by LeleCao** [dfreeman/ember-ace#19]

**Comment by LeleCao** [comment]
I am a small rookie

**Comment by dfreeman** [comment]
It's almost certainly not compatible with Ember 1.3 — it's possible it's compatible with Ember 1.13, though, but honestly I'm not sure. Currently the tests run against [the Ember 2.4 and 2.8 LTS releases, as well as the current stable, beta and canary builds](https://github.com/dfreeman/ember-ace/blob/master/config/ember-try.js).

At this point most new addons are only testing back to 2.8, so in general I would expect a lot of the ecosystem not to work with 1.x releases.
