### ISSUE TITLE
using a theme and mode

### ISSUE THREAD

**Issue by ghost** [dfreeman/ember-ace#2]
hi, very nice plugin

i have one question, how do i choose a theme and a mode i want to use? its not able to find the file i think

thanks

**Comment by ghost** [comment]
found it, and working well

**Comment by dfreeman** [comment]
Glad to hear you found it! I've also updated the section at the bottom of the README to link directly to the Ace source to make it easier to find the available themes, modes, etc.

**Comment by aaronucsd** [comment]
I have the same question. Even from the readme i'm not sure why the below isn't working. DO we need to explicitly install the modes and themes we want to use?

```
{{ember-ace lines=35 value="value" theme="chaos" mode="ace/mode/javascript"}}```

**Comment by aaronucsd** [comment]
nevermind it seems i need to add the modes and themes i want to use in the `ember-cli-build.js` and also tell the component which one i want as well in the template. Also i keep forgetting you need to reserve once edit the `ember-cli-build.js` file.

    ace: {
      themes: ['ambiance', 'chaos'],
      modes: ['yml'],
      workers: ['yml']
    }

{{ember-ace lines=35 value="value" theme="chaos" mode="ace/mode/yml"}}
