### ISSUE TITLE
Autocompletion

### ISSUE THREAD

**Issue by Louismac** [dfreeman/ember-ace#29]
Hi

First of all, thanks for making this plugin.

I've been struggling with an issue and the only way I've been able to fix it by changing the source, which I thought cant be right. 

Basically, the only way I've been able to get auto completion to work (the basic completer which searches for seen text in the document, not suggested completions) is by adding 

editor.setOption("enableBasicAutocompletion", true)

Before 

editor.completers = this._buildCompleters(editor);

in _instantiateEditors in addons/components/ace-editor.js . Setting this option adds 3 completers to editor.completers property, and these need to exist before _buildCompleters is called for them to work in the actual Ace Editor, and as this is the only place _buildCompleters is called, its the only way I've got it to work. 

Am I missing something obvious?

Thanks in advance

**Comment by dfreeman** [comment]
Hi @Louismac,

You're not missing anything, it's just a good old-fashioned bug on this end! I've just opened #30 to fix the issue, and I'll plan to cut a quick release including that sometime today.

**Comment by Louismac** [comment]
Thanks!
