### ISSUE TITLE
How to redraw after rolling back a model

### ISSUE THREAD

**Issue by drauschenbach** [dfreeman/ember-ace#31]
I have an Ember Data model that holds my script source code. On my toolbar is a Save button that is enabled when my model is dirty, and a Cancel button to rollback dirty edits.

When I rollbackAttributes() on my model, Ember Ace does not redraw and continues to show the stale content.

```handlebars
  {{ember-ace lines=20
    mode='ace/mode/lua'
    theme='ace/theme/tomorrow'
    value=(get model.properties property)
    update=(action 'propertyChanged')
  }}
```

I also tried using a mutating binding and that didn't help:

```handlebars
  {{ember-ace lines=20
    mode='ace/mode/lua'
    theme='ace/theme/tomorrow'
    value=(mut (get model.properties property))
  }}
```

**Comment by dfreeman** [comment]
🤔 I'd be surprised if this actually had anything to do with this addon—if you put `{{get model.properties property}}` in your template so that the script source is showing up in plain text as well, does that update when you call `rollbackAttributes()`?

**Comment by drauschenbach** [comment]
You're right, this is a problem in how I'm wiring the binding, and the same problem manifests outside of Ember Ace. Thanks Dan!
