### ISSUE TITLE
Updating the value attribute causes update to trigger twice.

### ISSUE THREAD

**Issue by bdiz** [dfreeman/ember-ace#6]
Seems updating the value attribute causes update to trigger twice. Once with an empty string (not expected), and second with the new value (expected). Since I am using update=(action (mut myValue)), I get this error in the console "Assertion Failed: You modified "myValue" twice on [object Object] in a single render. It was rendered in "component:ember-ace" and modified in "component:ember-ace". This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details."

I've also tried providing an action to update and setting myValue in there. Same error results.

Is it possible to stop the action from firing with the empty string when changing value from a parent component?

**Comment by dfreeman** [comment]
Hi @bdiz — thanks for reporting this; it definitely sounds like a bug. It looks like Ace's `editor.setValue` first clears the editor, then fills in the new value, triggering two change events.

The dummy app in this repo uses `{{ember-ace value=value update=(action (mut value))}}`, and I'm not seeing the double modification error from Ember, but the `update` action definitely fires twice as you describe. I'm doing some work in here on autocompletion today anyway; I'll aim to fix the double `update` as part of that.

**Comment by dfreeman** [comment]
> Once with an empty string (not expected), and second with the new value (expected).

On reflection, I would actually expect setting the `value` attribute not to trigger `update` at all. This is consistent with how native input elements work, as well as DDAU Ember components like `ember-one-way-controls`.

Will it be a problem for your use case if I go that route?

**Comment by bdiz** [comment]
That route sounds good to me. Thanks.
